# This file was generated by GoReleaser. DO NOT EDIT.
cask "tabdriver" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "929c15d23a6f146fb0596c494f2f6d5bfd9ec730bf6df0391e75bf38903205a8"
      url "https://github.com/trajche/tabdriver/releases/download/v#{version}/tabdriver_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa473e90a6cd10762d5288e881d6ca55ca1cb5f4550142c049bc398a9e093266"
      url "https://github.com/trajche/tabdriver/releases/download/v#{version}/tabdriver_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8c74dac766875e93e0bf1e8de68a61991a8c0fa6cf42a8135279454cc7b825cb"
      url "https://github.com/trajche/tabdriver/releases/download/v#{version}/tabdriver_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c8c54f269efaf6fdf900928c1fd350d72c71edca7ed1c97ca48efde886f320c"
      url "https://github.com/trajche/tabdriver/releases/download/v#{version}/tabdriver_linux_amd64.tar.gz"
    end
  end

  name "tabdriver"
  desc "Let AI agents drive your real browser, with your logins, while you watch"
  homepage "https://github.com/trajche/tabdriver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tabdriver"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tabdriver"]
    end
    system_command "#{HOMEBREW_PREFIX}/bin/tabdriver", args: ["install"]
  end

  uninstall_preflight do
    system_command "#{staged_path}/tabdriver", args: ["uninstall"], must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Registered with your browsers. Next: install the browser extension and add `tabdriver mcp`
    to your agent (run `tabdriver` for the exact lines). https://github.com/trajche/tabdriver
  EOS
end
