# This file was generated by GoReleaser. DO NOT EDIT.
cask "tabdriver" do
  if respond_to?(:postflight_steps)
    postflight_steps do
      run "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "tabdriver"], chdir: ".", must_succeed: false,
                            print_stderr: false, writable_paths: ["tabdriver"], writable_base: :staged_path
      run "bin/tabdriver", base: :homebrew_prefix, args: ["install"],
                           writable_paths: ["Library/Application Support", ".tabdriver"], writable_base: :home
    end
    uninstall_preflight_steps do
      run "tabdriver", base: :staged_path, args: ["uninstall"], must_succeed: false,
                       writable_paths: ["Library/Application Support", ".tabdriver"], writable_base: :home
    end
  else
    postflight do
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tabdriver"] if OS.mac?
      system_command "#{HOMEBREW_PREFIX}/bin/tabdriver", args: ["install"]
    end
    uninstall_preflight do
      system_command "#{staged_path}/tabdriver", args: ["uninstall"], must_succeed: false
    end
  end

  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "2c4c5716fd0f896aa7f82aa8dc28ab6214dfc9fc45b916dcd8dcf3e889052f8e"
      url "https://github.com/trajche/tabdriver/releases/download/v#{version}/tabdriver_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "83edcadbe080965c558f6568a3b112ec36dc17d23a9dd796b3ab028da77e6127"
      url "https://github.com/trajche/tabdriver/releases/download/v#{version}/tabdriver_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "97bf07248ffb2911e763576c127ebe620d8863cd169eed2e7af20b87f37558aa"
      url "https://github.com/trajche/tabdriver/releases/download/v#{version}/tabdriver_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c7315f24defa9436b2dbd88cfa6bf039515f5d8777f1e0806861011996df9030"
      url "https://github.com/trajche/tabdriver/releases/download/v#{version}/tabdriver_linux_amd64.tar.gz"
    end
  end

  name "tabdriver"
  desc "Let AI agents drive your real browser, with your logins, while you watch"
  homepage "https://github.com/trajche/tabdriver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tabdriver"

  # No zap stanza required

  caveats <<~EOS
    Registered with your browsers. Next: install the browser extension and add `tabdriver mcp`
    to your agent (run `tabdriver` for the exact lines). https://github.com/trajche/tabdriver
  EOS
end
