# This file was generated by GoReleaser. DO NOT EDIT.
cask "tabdriver" do
  version "0.2.4"

  on_macos do
    on_arm do
      sha256 "79a85d3b5afd9363c6257a9871232d15a504efff310d8198b960c6e8c71edad6"
      url "https://github.com/trajche/tabdriver/releases/download/v#{version}/tabdriver_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a3858459b8cba1f71315f8166a68def93fd6c13058382e849a6c30a1425fce6d"
      url "https://github.com/trajche/tabdriver/releases/download/v#{version}/tabdriver_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8012b855034d2770665bab01f6dbd528165c9483c75fbde8059b7d2d1abcb204"
      url "https://github.com/trajche/tabdriver/releases/download/v#{version}/tabdriver_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "276a2b8af9ee6bfa710f0e89c967fcdf3e0431b00970756060636bebd670addd"
      url "https://github.com/trajche/tabdriver/releases/download/v#{version}/tabdriver_linux_amd64.tar.gz"
    end
  end

  name "tabdriver"
  desc "Let AI agents drive your real browser, with your logins, while you watch"
  homepage "https://github.com/trajche/tabdriver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tabdriver"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tabdriver"]
    end
    system_command "#{HOMEBREW_PREFIX}/bin/tabdriver", args: ["install"]
  end

  uninstall_preflight do
    system_command "#{staged_path}/tabdriver", args: ["uninstall"], must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Registered with your browsers. Next: install the browser extension and add `tabdriver mcp`
    to your agent (run `tabdriver` for the exact lines). https://github.com/trajche/tabdriver
  EOS
end
